---
title: "edld610_lab4"
author: "Cameron Kay, Lea Frank, Ashley Miller"
date: "2/5/2019"
output: html_document
---

```{r setup, include = FALSE}
# install github packages
#devtools::install_github("wilkelab/cowplot")
#install.packages("colorspace", repos = "http://R-Forge.R-project.org")
#devtools::install_github("clauswilke/colorblindr")

# load packages
library(tidyverse)
library(magrittr)
library(rio)
library(here)
library(colorblindr)
library(colorspace)
library(cowplot)
library(ggmap)
library(maps)
library(mapdata)

# load data
honey_data <- import(here("data/honeyproduction.csv"), setclass = "tibble") %>%
  janitor::clean_names()
```

```{r part_1}

```

```{r part_2}

```

```{r part_3}

```

```{r part_4}

```

```{r part_5}

```

### Create at least one more plot of your choosing using color to distinguish, represent data values, or highlight. If you are interested in producing maps, I would recommend joining the data with the output from ggplot2::map_data("state"). But be careful with keys and that you don’t end up with a many-to-many join. See here for additional help

```{r part_6}
# load map data
map_data <- ggplot2::map_data("state")

# join honey_data and map_data
## find unique keys
honey_data %>%
  count(state, year) %>% 
  filter(n > 1)

map_data %>%
  count(order) %>% 
  filter(n > 1)

# summarize data and join
cam_data <- honey_data %>%
  group_by(state) %>%
  summarize(totalprod_m = mean(totalprod, na.rm = TRUE)) %>%
  mutate(totalprod_m = totalprod_m / 1000000) %>%
  rowwise() %>%
  mutate(region = state.name[grep(state, state.abb)],
         region = tolower(region)) %>%
  left_join(map_data, by = "region")

# check lengths
length(unique(honey_data$state))
length(unique(cam_data$region))

# plot
ggplot(data = cam_data) + 
  geom_polygon(aes(x = long, y = lat, fill = totalprod_m, group = group), color = "white") + 
  coord_fixed(1.3) +
  scale_fill_continuous_sequential("Oranges") +
  labs(title = "Average honey production for each state from 1998 to 2012",
       x = "",
       y = "",
       fill = "Total production (millions)") +
  theme_void() +
  theme(legend.position = "bottom")
```
